package entities;

public enum TypeLocation {
    GITE_RURAL,
    GITE_COLLECTIFS,
    MOBILHOME,
    CHALET,
    SALE_ANIMATION,
    EMPLACEMENT,
    APPARTEMENT_F2,
    APPARTEMENT_F3,
    EMPLACEMENT_CAMPING_CLASSIQUE,
    EMPLACEMENT_CAMPING_COMFORT,
    EMPLACEMENT_CAMPING_GRAND_COMFORT
}