package fr.gadoy.camping.entities;
// Generated 27 juin 2019 16:28:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name="bill"
    ,catalog="camping"
)
public class Bill  implements java.io.Serializable {


     private int id;
     private Date dateCreation;
     private byte datePaid;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public Bill() {
    }

	
    public Bill(int id, Date dateCreation, byte datePaid) {
        this.id = id;
        this.dateCreation = dateCreation;
        this.datePaid = datePaid;
    }
    public Bill(int id, Date dateCreation, byte datePaid, Set<Booking> bookings) {
       this.id = id;
       this.dateCreation = dateCreation;
       this.datePaid = datePaid;
       this.bookings = bookings;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateCreation", nullable=false, length=10)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    
    @Column(name="datePaid", nullable=false)
    public byte getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(byte datePaid) {
        this.datePaid = datePaid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bill")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


