package fr.gadoy.camping.entities;
// Generated 27 juin 2019 16:28:57 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Meal generated by hbm2java
 */
@Entity
@Table(name="meal"
    ,catalog="camping"
)
public class Meal  implements java.io.Serializable {


     private MealId id;
     private Booking booking;
     private Mealtype mealtype;
     private User user;
     private String price;

    public Meal() {
    }

	
    public Meal(MealId id, Booking booking, Mealtype mealtype, User user) {
        this.id = id;
        this.booking = booking;
        this.mealtype = mealtype;
        this.user = user;
    }
    public Meal(MealId id, Booking booking, Mealtype mealtype, User user, String price) {
       this.id = id;
       this.booking = booking;
       this.mealtype = mealtype;
       this.user = user;
       this.price = price;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="bookingId", column=@Column(name="Booking_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="User_id", nullable=false) ), 
        @AttributeOverride(name="mealTypeId", column=@Column(name="MealType_id", nullable=false) ) } )
    public MealId getId() {
        return this.id;
    }
    
    public void setId(MealId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Booking_id", nullable=false, insertable=false, updatable=false)
    public Booking getBooking() {
        return this.booking;
    }
    
    public void setBooking(Booking booking) {
        this.booking = booking;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MealType_id", nullable=false, insertable=false, updatable=false)
    public Mealtype getMealtype() {
        return this.mealtype;
    }
    
    public void setMealtype(Mealtype mealtype) {
        this.mealtype = mealtype;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="price", length=45)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


