package fr.gadoy.camping.entities;
// Generated 27 juin 2019 16:28:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mealtype generated by hbm2java
 */
@Entity
@Table(name="mealtype"
    ,catalog="camping"
)
public class Mealtype  implements java.io.Serializable {


     private int id;
     private Set<Meal> meals = new HashSet<Meal>(0);

    public Mealtype() {
    }

	
    public Mealtype(int id) {
        this.id = id;
    }
    public Mealtype(int id, Set<Meal> meals) {
       this.id = id;
       this.meals = meals;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mealtype")
    public Set<Meal> getMeals() {
        return this.meals;
    }
    
    public void setMeals(Set<Meal> meals) {
        this.meals = meals;
    }




}


