package fr.gadoy.camping.entities;
// Generated 27 juin 2019 16:28:57 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MealId generated by hbm2java
 */
@Embeddable
public class MealId  implements java.io.Serializable {


     private int bookingId;
     private int userId;
     private int mealTypeId;

    public MealId() {
    }

    public MealId(int bookingId, int userId, int mealTypeId) {
       this.bookingId = bookingId;
       this.userId = userId;
       this.mealTypeId = mealTypeId;
    }
   


    @Column(name="Booking_id", nullable=false)
    public int getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(int bookingId) {
        this.bookingId = bookingId;
    }


    @Column(name="User_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="MealType_id", nullable=false)
    public int getMealTypeId() {
        return this.mealTypeId;
    }
    
    public void setMealTypeId(int mealTypeId) {
        this.mealTypeId = mealTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MealId) ) return false;
		 MealId castOther = ( MealId ) other; 
         
		 return (this.getBookingId()==castOther.getBookingId())
 && (this.getUserId()==castOther.getUserId())
 && (this.getMealTypeId()==castOther.getMealTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBookingId();
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getMealTypeId();
         return result;
   }   


}


