package fr.gadoy.camping.entities;
// Generated 27 juin 2019 16:28:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Option generated by hbm2java
 */
@Entity
@Table(name="option"
    ,catalog="camping"
)
public class Option  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Location> locations = new HashSet<Location>(0);
     private Set<Selectedoption> selectedoptions = new HashSet<Selectedoption>(0);

    public Option() {
    }

	
    public Option(int id) {
        this.id = id;
    }
    public Option(int id, String name, Set<Location> locations, Set<Selectedoption> selectedoptions) {
       this.id = id;
       this.name = name;
       this.locations = locations;
       this.selectedoptions = selectedoptions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="location_has_option", catalog="camping", joinColumns = { 
        @JoinColumn(name="Option_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Location_id", nullable=false, updatable=false) })
    public Set<Location> getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set<Location> locations) {
        this.locations = locations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="option")
    public Set<Selectedoption> getSelectedoptions() {
        return this.selectedoptions;
    }
    
    public void setSelectedoptions(Set<Selectedoption> selectedoptions) {
        this.selectedoptions = selectedoptions;
    }




}


