package fr.gadoy.camping.entities;
// Generated 27 juin 2019 16:28:57 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Selectedoption generated by hbm2java
 */
@Entity
@Table(name="selectedoption"
    ,catalog="camping"
)
public class Selectedoption  implements java.io.Serializable {


     private SelectedoptionId id;
     private Booking booking;
     private Option option;
     private int amount;

    public Selectedoption() {
    }

    public Selectedoption(SelectedoptionId id, Booking booking, Option option, int amount) {
       this.id = id;
       this.booking = booking;
       this.option = option;
       this.amount = amount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="optionId", column=@Column(name="Option_id", nullable=false) ), 
        @AttributeOverride(name="bookingId", column=@Column(name="Booking_id", nullable=false) ) } )
    public SelectedoptionId getId() {
        return this.id;
    }
    
    public void setId(SelectedoptionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Booking_id", nullable=false, insertable=false, updatable=false)
    public Booking getBooking() {
        return this.booking;
    }
    
    public void setBooking(Booking booking) {
        this.booking = booking;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Option_id", nullable=false, insertable=false, updatable=false)
    public Option getOption() {
        return this.option;
    }
    
    public void setOption(Option option) {
        this.option = option;
    }

    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


