package fr.gadoy.camping.entities;
// Generated 27 juin 2019 16:28:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="camping"
)
public class User  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String phone;
     private String mobile;
     private Date birthDate;
     private String email;
     private String street;
     private String postalCode;
     private String city;
     private String civility;
     private String numberPlate;
     private Set<Meal> meals = new HashSet<Meal>(0);
     private Set<Booking> bookings = new HashSet<Booking>(0);
     private Set<Usertype> usertypes = new HashSet<Usertype>(0);

    public User() {
    }

	
    public User(int id, String firstName, String lastName) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public User(int id, String firstName, String lastName, String phone, String mobile, Date birthDate, String email, String street, String postalCode, String city, String civility, String numberPlate, Set<Meal> meals, Set<Booking> bookings, Set<Usertype> usertypes) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.mobile = mobile;
       this.birthDate = birthDate;
       this.email = email;
       this.street = street;
       this.postalCode = postalCode;
       this.city = city;
       this.civility = civility;
       this.numberPlate = numberPlate;
       this.meals = meals;
       this.bookings = bookings;
       this.usertypes = usertypes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="firstName", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone", length=10)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="mobile", length=10)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthDate", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="email", length=128)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="street")
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="postalCode", length=5)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="civility", length=45)
    public String getCivility() {
        return this.civility;
    }
    
    public void setCivility(String civility) {
        this.civility = civility;
    }

    
    @Column(name="numberPlate", length=65535)
    public String getNumberPlate() {
        return this.numberPlate;
    }
    
    public void setNumberPlate(String numberPlate) {
        this.numberPlate = numberPlate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Meal> getMeals() {
        return this.meals;
    }
    
    public void setMeals(Set<Meal> meals) {
        this.meals = meals;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_has_booking", catalog="camping", joinColumns = { 
        @JoinColumn(name="User_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Booking_id", nullable=false, updatable=false) })
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Usertype> getUsertypes() {
        return this.usertypes;
    }
    
    public void setUsertypes(Set<Usertype> usertypes) {
        this.usertypes = usertypes;
    }




}


